name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lowercase image name
        run: |
          # split GITHUB_REPOSITORY (owner/repo) then lowercase both parts
          OWNER_LOWER=$(echo "${GITHUB_REPOSITORY}" | cut -d/ -f1 | tr '[:upper:]' '[:lower:]')
          REPO_LOWER=$(echo "${GITHUB_REPOSITORY}" | cut -d/ -f2 | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_REF=${REGISTRY}/${OWNER_LOWER}/${REPO_LOWER}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag PocketBase image
        run: |
          TAG=${GITHUB_SHA::7}
          docker build \
            -f Dockerfile-pb \
            -t $IMAGE_REF:$TAG \
            .

      - name: Push the Docker image
        run: |
          docker push $IMAGE_REF:$TAG
